#! /bin/sh
go_version=1.25.3

tag=$go_version$suffix

echo "*** building tag $tag"

img=mcluseau/golang-builder:$tag

docker build --push -t $img --build-arg go_version=${go_version} . &&

sed -i "/^from/s/:.* as build/:$tag as build/" README.md

git commit -am "version $tag"
git tag -am $tag $tag

