#! /bin/sh
go_version=1.21.6

tag=$go_version$suffix

echo "*** building tag $tag"

img=mcluseau/golang-builder:$tag

docker build --network host -t $img --build-arg go_version=${go_version} . &&
docker push $img

sed -i "/^from/s/:.* as build/:$tag as build/" README.md

git commit -am "version $tag"
git tag -am $tag $tag

